# This is a basic workflow to help you get started with Actions

name: MarkDown işleme

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Generate HTML from Markdown
        uses: ldeluigi/markdown-docs@latest
        with:
          src: kaynak
          dst: kitap
          title: Markdown Docs
          language: tr
          icon: library
          primary-color: indigo
          secondary-color: indigo
          hide-repository: false
